# Bu fayl Railway'ga tizim darajasidagi paketlarni o'rnatishni aytadi.
[phases.setup]
# Audio qayta ishlash uchun ffmpeg va Python 3.10 kerak bo'ladi.
# Shuningdek, yt-dlp uchun kerak bo'ladigan qo'shimcha paketlar
nixPkgs = ["ffmpeg", "python310", "python310Packages.pip", "yt-dlp", "git"]

[phases.install]
# Python paketlarini o'rnatish
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
# Botni ishga tushirish
cmd = "python bot.py"
